name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install OpenCV
      run: sudo apt-get install libopencv-dev
    - name: Build and run C++ code
      run: |
        mkdir build
        cd build
        cmake ..
        make